matrix: 
  include:
    if: branch = dev OR branch = main
    type: pull_request
    - language: node_js
    node_js:
      - 14
    cache: 
      directories:
        - client/node_modules
    script: 
      - cd client
      - npm install
      - npm run lint
      - npm run test:unit
      - cd ..
