import deepFreeze from 'deep-freeze';
import generatedBackendConstants from '@/../generated/backend_constants.json';

/**
 * Note that these are generated by running `npm run setup` first.
 *
 * @typedef HMModel
 */
const BACKEND_CONSTANTS = deepFreeze(generatedBackendConstants);

export default BACKEND_CONSTANTS;
