const plotNames = {
  dndm: 'dn/dm',
  dndlnm: 'dn/dln(m)',
  dndlog10m: 'dn/dlog10(m)',
  fsigma: 'f(σ)',
  sigma: 'σ (mass variance)',
  lnsigma: 'ln(1/σ)',
  n_eff: 'Effective Spectral Index',
  ngtm: 'n(>m)',
  rho_ltm: 'ρ(<m)',
  rho_gtm: 'ρ(>m)',
  transfer_function: 'Transfer Function',
  power: 'Power Spectrum',
  delta_k: 'Dimensionless Power Spectrum',
  nonlinear_delta_k: 'Non-linear dimensionless power spectrum (HALOFIT)',
  nonlinear_power: 'Non-linear power spectrum (HALOFIT)',
  corr_linear_mm: 'Linear matter correlation function',
  halo_bias: 'Halo Bias',
  cmz_relation: 'Halo Concentration-Mass Relation',
  total_occupation: 'Tracer occupation',
  central_occupation: 'Occupation of central component',
  satellite_occupation: 'Occupation of satellite component',
  radii: 'Radii of spherical regions',
  tracer_cmz_relation: 'Tracer conentration-mass relation',
  power_auto_matter: 'Matter-matter power spectrum',
  power_2h_auto_matter: '2-halo matter-matter power spectrum',
  power_1h_auto_matter: '1-halo matter-matter power spectrum',
  power_auto_tracer: 'Tracer power spectrum',
  power_2h_auto_tracer: '2-halo tracer-tracer power spectrum',
  power_1h_auto_tracer: '2-halo tracer-tracer power spectrum',
  power_1h_cs_auto_tracer: '1-halo central-satellite tracer power spectrum',
  power_1h_ss_auto_tracer: '1-halo satellite-satellite tracer power spectrum',
  power_cross_tracer_matter: 'Matter-tracer power spectrum',
  power_1h_cross_tracer_matter: '1-halo tracer-matter power spectrum',
  power_2h_cross_tracer_matter: '2-halo matter-tracer power spectrum',
  corr_auto_matter: 'Matter-matter correlation function',
  corr_2h_auto_matter: '2-halo matter-matter correlation function',
  corr_1h_auto_matter: '1-halo matter-matter correlation function',
  corr_auto_tracer: 'Tracer-tracer correlation function',
  corr_2h_auto_tracer: '2-halo tracer-tracer correlation function',
  corr_1h_auto_tracer: '1-halo tracer-tracer correlation function',
  corr_1h_cs_auto_tracer: '1-halo central-satellite tracer correlation function',
  corr_1h_ss_auto_tracer: '1-halo satellite-satellite tracer correlation function',
  corr_cross_tracer_matter: 'Matter-tracer correlation function',
  corr_1h_cross_tracer_matter: '1-halo matter-tracer correlation function',
  corr_2h_cross_tracer_matter: '2-halo matter-tracer correlation function',
  sd_bias_correction: 'Scale-dependent bias correction',
};

const xLabelNames = {
  'Mass $(M_{\\odot}h^{-1})$': 'Mass Function',
  'Wavenumber, $k$ [$h$/Mpc]': 'Wavenumber',
  'Scale, $r$ [Mpc/$h$]': 'Scale',
  'Fourier Scale, $k$ [$h$/Mpc]': 'Fourier Scale',
};

export { plotNames, xLabelNames };
