version: '3.5'

services:
  thehalomod-server:
    build: .
    ports: 
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    links:
      - redis
    container_name: hmf-server
    environment: 
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
#    networks:
#      - nginx_network
    env_file: 
      - '${ENV_FILE}'

'''  nginx:
    image: nginx:1.13
    ports: 
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /home/locoadmin/webhost/:/webhost
    depends_on:
      - thehalomod-server
    networks:
      - nginx_network
'''

  redis:
    image: "redis"
    container_name: hmf-redis-cache
    expose: 
      - 6379

'''
networks:
  nginx_network:
    driver: bridge
'''