version: '3.5'

services:
  thehalomod-server:
    build: .
    ports: 
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    links:
      - redis
    container_name: hmf-server
    # The default stop signal for flask apps is SIGINT, while by default
    # docker uses SIGTERM
    stop_signal: SIGINT
    environment: 
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      # Development mode on for now to find issues
      - FLASK_ENV="development"
      # Debug mode on for now to find issues
      - FLASK_DEBUG=True
      - FLASK_APP=halomod_app

  redis:
    image: "redis"
    container_name: hmf-redis-cache
    expose: 
      - 6379