version: '3.5'

services:
  thehalomod-server:
    build: .
    ports:
      - "5000:5000"
    links:
      - redis
    container_name: hmf-server
  redis:
    image: "redis"
    container_name: hmf-redis-cache
    expose: 
      - 6379
