version: '3.5'

services:
  thehalomod-server:
    build: .
    ports: 
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    links:
      - redis
    container_name: hmf-server
    environment: 
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}

  redis:
    image: "redis"
    container_name: hmf-redis-cache
    expose: 
      - 6379
