# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# This workflow will run lint and unit tests for the vue client on every push.

name: Client CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-e
          ${{ runner.os }}-

    - name: Set up Python 3.9.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
  
    - name: Python Caching
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        # Makes the hashing depend on changes to requirements.txt and python version
        key: ${{ runner.os }}${{ env.pythonLocation }}-${{ hashFiles('server/requirements.txt') }}-py3.9.5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # gfortran setup for camb
    - name: Setup gfortran
      run: |
        sudo apt-get install gfortran-8
        mkdir -p gfortran-symlinks
        ln -s /usr/bin/gfortran-8 gfortran-symlinks/gfortran
        export PATH=$PWD/gfortran-symlinks:$PATH

    - name: Generate constants    
      run: sh generate_client_files.sh

    - name: Run Tests
      run: |
        cd client
        yarn install --frozen-lockfile
        yarn lint
        yarn test
