# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Client Deployment

# Deploy on push temporarily while modifying the deployment process.
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Require that the 'test' job completes first. This SHOULD make it so that
    # the constants are already built into the client folder.
    needs: test
    defaults:
      run:
        working-directory: client

    # Checks out the code?
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    # Deploys the current client folder after testing to netlify.
    name: 'Deploy to Netlify'
    steps:
    - uses: jsmrcaga/action-netlify-deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_OAUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true