# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server Deployment

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Require that the 'test' job completes first
    needs: test
    defaults:
      run:
        working-directory: server

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script:  |
          mkdir /opt/HaloModServer-SPA
          cd /opt/HaloModServer-SPA
          git clone https://github.com/halomod/TheHaloMod-SPA
          git pull origin master
          git status
          # Stop the server with docker-compose down
          # start the server with python3 dockerStart.py -p --url localhost --port 5000
