# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# This workflow deploys the server to ASU's servers.

name: Server Deployment

on: 
  push:
    # Another branch can be added below if the server is being tested, but note
    # that if the site is deployed, or anyone else is testing it, it will be 
    # changed for everyone.
    branches:
      - main
      - autoRestart
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: DeployServer
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVERKEY }}
        port: ${{ secrets.PORT }}
        script:  |
          export FLASK_RUN_HOST=0.0.0.0
          export FLASK_RUN_PORT=8010
          export FLASK_KEY=${{ secrets.FLASK_KEY }}
          export MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          cd ./TheHaloMod-SPA/server
          docker-compose down
          cd ../..
          rm -r ./TheHaloMod-SPA
          git clone https://github.com/halomod/TheHaloMod-SPA
          cd ./TheHaloMod-SPA
          git fetch origin -a

          # Clone the branch that this workflow is being deployed for
          git checkout ${{ steps.extract_branch.outputs.branch }}

          git status
          cd ./server
          ls
          docker-compose up --build --remove-orphans -d
