# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server Deployment

on: 
  push:
    branches:
      - testServerDeployment

jobs:
  build:
    runs-on: ubuntu-latest
    # Require that the 'test' job completes first
    #needs: test
    #defaults:
    #  run:
    #    working-directory: server

    steps:
    - name: DeployServer
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVERKEY }}
        port: ${{ secrets.PORT }}
        script:  |
          ls
          docker-compose down
          rm -r ./TheHaloMod-SPA
          git clone https://github.com/halomod/TheHaloMod-SPA
          cd ./TheHaloMod-SPA
          git pull
          git status
          # Stop the server with docker-compose down
          cd server
          python3 dockerStart.py -p --url localhost --port 8010
