# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server Deployment

on: 
  push:
    branches:
      - main
      - US321-CompleteDeployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: DeployServer
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVERKEY }}
        port: ${{ secrets.PORT }}
        script:  |
          export FLASK_RUN_HOST=0.0.0.0
          export FLASK_RUN_PORT=8010
          export FLASK_KEY=${{ secrets.FLASK_KEY }}
          cd ./TheHaloMod-SPA/server

          printf "\nserver directory contents:\n" 
          ls
          printf "\n"

          docker-compose down
          cd ../..
          rm -r ./TheHaloMod-SPA
          git clone https://github.com/halomod/TheHaloMod-SPA
          cd ./TheHaloMod-SPA
          git fetch origin -a
          git checkout ${{ steps.extract_branch.outputs.branch }}
          git status
          # Stop the server with docker-compose down
          cd ./server
          ls
          docker-compose up --build --remove-orphans -d
