# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Server CI

on: [push, workflow_dispatch]

jobs:
  test:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest

    services:
      thehalomod-server:
        build: .
        ports: 
          - 5000:5000
        links:
          - redis
        container_name: hmf-server
        environment: 
          - FLASK_RUN_PORT=5000
          - FLASK_RUN_HOST=127.0.0.1
        networks:
          - nginx_network

      nginx:
        image: nginx:1.13
        ports: 
          - 443:443
        volumes:
          - ./nginx:/etc/nginx/conf.d
          - /home/locoadmin/webhost/:/webhost
        depends_on:
          - thehalomod-server
        networks:
          - nginx_network

      redis:
        image: "redis"
        container_name: hmf-redis-cache
        expose: 
          - 6379

    networks:
      nginx_network:
        driver: bridge


    steps:
    - uses: actions/checkout@v2
    - name: Setup gfortran
      run: |
        sudo apt-get install gfortran-8
        mkdir -p gfortran-symlinks
        ln -s /usr/bin/gfortran-8 gfortran-symlinks/gfortran
        export PATH=$PWD/gfortran-symlinks:$PATH
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Python Caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('server/requirements.txt') }}

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        . ./run.sh --install
    
    - name: Lint
      run: . ./run.sh --lint
    
    - name: Test
      run: | 
        . ./run.sh --test
